### ISSUE TITLE
Stack seen launching jnlp and pre-installed application

### ISSUE THREAD

**Issue by AdamStuart** [PathVisio/pathvisio#101]
org.osgi.framework.BundleException: Unresolved constraint in System Bundle:null
	at org.apache.felix.framework.Felix.init(Felix.java:742)
	at org.apache.felix.framework.Felix.init(Felix.java:624)
	at org.apache.felix.framework.Felix.start(Felix.java:963)
	at org.pathvisio.launcher.PathVisioMain$1.doInBackground(Unknown Source)
	at org.pathvisio.launcher.PathVisioMain$1.doInBackground(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by AdamStuart** [comment]
had to download zip, and add executable privileges to the script:

 chmod u+x pathvisio.sh

**Comment by mkutmon** [comment]
as mentioned in the email - I think this is probably related to Java 10 issues. PathVisio does not support Java 10 yet. Can you try installing Java 8 and let me know if it works then?

**Comment by khanspers** [comment]
I saw this with Java 8.

**Comment by mkutmon** [comment]
Hmm strange. @AdamStuart you also work on MacOSX or on Linux?
