### ISSUE TITLE
weird error message: database not set, but is given

### ISSUE THREAD

**Issue by egonw** [PathVisio/pathvisio#106]
![image](https://user-images.githubusercontent.com/26721/49328358-79e49a80-f56f-11e8-830a-7a98bbd16b0b.png)

**Comment by egonw** [comment]
I was able to change it to `Ensembl Human`, close the dialog, open it again, and then change it to the proper `Ensembl`.

**Comment by egonw** [comment]
This is with the Ensembl v91 Derby and on the command line I get this stacktrace:

```
Exception in thread "AWT-EventQueue-1" java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
        at java.util.ArrayList$Itr.next(ArrayList.java:859)
        at org.pathvisio.gui.DataSourceModel.fireEvent(DataSourceModel.java:69)
        at org.pathvisio.gui.DataSourceModel.setSelectedItem(DataSourceModel.java:81)
        at org.pathvisio.gui.dialogs.DataNodeDialog.applyAutoFill(DataNodeDialog.java:118)
        at org.pathvisio.gui.dialogs.DataNodeDialog.access$100(DataNodeDialog.java:73)
        at org.pathvisio.gui.dialogs.DataNodeDialog$1.done(DataNodeDialog.java:188)
```

**Comment by egonw** [comment]
With Java8 (OpenJDK).

**Comment by mkutmon** [comment]
@egonw I cannot reproduce this :(
Do you have more information about when this occurred?

**Comment by egonw** [comment]
Ignore for now. I will try to reproduce later this week.
