### ISSUE TITLE
Pathway WP2909 cannot be read, due to BioPax issue

### ISSUE THREAD

**Issue by egonw** [PathVisio/pathvisio#170]
```
  pathway: WP2909	111761
[   609.244] Info:  Start reading the XML file: /tmp/wp-cache/Arabidopsis thaliana/WP2909.gpml
[   609.289] Info:  Recognized format [Namespace: prefix "" is mapped to URI "http://pathvisio.org/GPML/2013a"]
Warn:  Unknown property: IRIS_ID
Error: Biopax element [Element: <bp:PublicationXref [Namespace: http://www.biopax.org/release/biopax-level3.owl#]/>] ignored
	java.lang.IllegalArgumentException: Property IRIS_ID is not valid for The gene for fragrance in rice <A href='http://www.ncbi.nlm.nih.gov/pubmed/http://rdlibrary.app.pmi//doc_num.php?explnum_id=70021'>PubMed http://rdlibrary.app.pmi//doc_num.php?explnum_id=70021</A>.: Property IRIS_ID is not valid for The gene for fragrance in rice <A href='http://www.ncbi.nlm.nih.gov/pubmed/http://rdlibrary.app.pmi//doc_num.php?explnum_id=70021'>PubMed http://rdlibrary.app.pmi//doc_num.php?explnum_id=70021</A>.
java.lang.IllegalArgumentException: Property IRIS_ID is not valid for The gene for fragrance in rice <A href='http://www.ncbi.nlm.nih.gov/pubmed/http://rdlibrary.app.pmi//doc_num.php?explnum_id=70021'>PubMed http://rdlibrary.app.pmi//doc_num.php?explnum_id=70021</A>.
	at org.pathvisio.core.biopax.BiopaxNode.addProperty(BiopaxNode.java:57)
	at org.pathvisio.core.biopax.BiopaxNode.loadXML(BiopaxNode.java:153)
	at org.pathvisio.core.biopax.BiopaxNode.fromXML(BiopaxNode.java:142)
	at org.pathvisio.core.biopax.BiopaxElement.refresh(BiopaxElement.java:80)
	at org.pathvisio.core.biopax.BiopaxElement.setBiopax(BiopaxElement.java:294)
	at org.pathvisio.core.model.GpmlFormat2013a.mapBiopax(GpmlFormat2013a.java:949)
	at org.pathvisio.core.model.GpmlFormat2013a.mapElement(GpmlFormat2013a.java:443)
	at org.pathvisio.core.model.GpmlFormatAbstract.readFromRoot(GpmlFormatAbstract.java:589)
	at org.pathvisio.core.model.GpmlFormat.readFromXmlImpl(GpmlFormat.java:182)
	at org.pathvisio.core.model.GpmlFormat.readFromXml(GpmlFormat.java:121)
	at org.pathvisio.core.model.Pathway.readFromXml(Pathway.java:734)
	at org.wikipathways.wp2rdf.WPREST2RDF.main(WPREST2RDF.java:235)
```

**Comment by mkutmon** [comment]
which pathvisio version are you using?

**Comment by egonw** [comment]
Not with PathVisio, but with GPMLRDF. However, because the problems seems to be in `org.pathvisio.core`, I filed it in this repo. It may also be automatically resolved with the upgrade. I just tried it with PathVisio 3.3, and that does not seem to have problems loading the pathway, but a similar exception does show up in the logs:

```
Error: Biopax element [Element: <bp:PublicationXref [Namespace: http://www.biopax.org/release/biopax-level3.owl#]/>] ignored
        java.lang.IllegalArgumentException: Property IRIS_ID is not valid for Removal of feedback inhibition of delta 1-pyrroline-5-carboxylate synthetase, a bifunctional enzyme catalyzing 
the first two steps of proline biosynthesis in plants. <A href='http://www.ncbi.nlm.nih.gov/pubmed/http://rdlibrary.app.pmi/doc_num.php?explnum_id=120751'>PubMed http://rdlibrary.app.pmi/do
c_num.php?explnum_id=120751</A>.: Property IRIS_ID is not valid for Removal of feedback inhibition of delta 1-pyrroline-5-carboxylate synthetase, a bifunctional enzyme catalyzing the first 
two steps of proline biosynthesis in plants. <A href='http://www.ncbi.nlm.nih.gov/pubmed/http://rdlibrary.app.pmi/doc_num.php?explnum_id=120751'>PubMed http://rdlibrary.app.pmi/doc_num.php?
explnum_id=120751</A>.
java.lang.IllegalArgumentException: Property IRIS_ID is not valid for Removal of feedback inhibition of delta 1-pyrroline-5-carboxylate synthetase, a bifunctional enzyme catalyzing the firs
t two steps of proline biosynthesis in plants. <A href='http://www.ncbi.nlm.nih.gov/pubmed/http://rdlibrary.app.pmi/doc_num.php?explnum_id=120751'>PubMed http://rdlibrary.app.pmi/doc_num.ph
p?explnum_id=120751</A>.
        at org.pathvisio.core.biopax.BiopaxNode.addProperty(Unknown Source)
        at org.pathvisio.core.biopax.BiopaxNode.loadXML(Unknown Source)
        at org.pathvisio.core.biopax.BiopaxNode.fromXML(Unknown Source)
        at org.pathvisio.core.biopax.BiopaxElement.refresh(Unknown Source)
        at org.pathvisio.core.biopax.BiopaxElement.setBiopax(Unknown Source)
        at org.pathvisio.core.model.GpmlFormat2013a.mapBiopax(Unknown Source)
        at org.pathvisio.core.model.GpmlFormat2013a.mapElement(Unknown Source)
        at org.pathvisio.core.model.GpmlFormatAbstract.readFromRoot(Unknown Source)
        at org.pathvisio.core.model.GpmlFormat.readFromXmlImpl(Unknown Source)
        at org.pathvisio.core.model.GpmlFormat.readFromXml(Unknown Source)
        at org.pathvisio.core.model.Pathway.readFromXml(Unknown Source)
        at org.wikipathways.client.WikiPathwaysClient.toPathway(WikiPathwaysClient.java:214)
        at org.pathvisio.wpclient.WikiPathwaysClientPlugin.openPathway(Unknown Source)
        at org.pathvisio.wpclient.WikiPathwaysClientPlugin$2.doInBackground(Unknown Source)
        at org.pathvisio.wpclient.WikiPathwaysClientPlugin$2.doInBackground(Unknown Source)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Warn:  Unknown property: IRIS_ID
```

**Comment by larsgw** [comment]
The `PublicationXref` elements contained `bp:IRIS_ID` elements which do not match the schema. These elements were removed in 2023: https://classic.wikipathways.org//index.php?pwTitle=Pathway%3AWP2909&diff=125975&oldid=117228.
