### ISSUE TITLE
Include file being read in NPE message

### ISSUE THREAD

**Issue by egonw** [PathVisio/pathvisio#49]
I'm getting on Jenkins a NPE when reading BioPAX from one of the GPML files:

    Exception in thread "main" org.pathvisio.core.model.ConverterException: class java.lang.NullPointerException: null
      at org.pathvisio.core.model.GpmlFormat2013a.mapBiopax(GpmlFormat2013a.java:925)
      at org.pathvisio.core.model.GpmlFormat2013a.mapElement(GpmlFormat2013a.java:442)
      at org.pathvisio.core.model.GpmlFormatAbstract.readFromRoot(GpmlFormatAbstract.java:589)
      at org.pathvisio.core.model.GpmlFormat.readFromXmlImpl(GpmlFormat.java:182)
      at org.pathvisio.core.model.GpmlFormat.readFromXml(GpmlFormat.java:121)
      at org.pathvisio.core.model.Pathway.readFromXml(Pathway.java:723)
      at org.wikipathways.wp2rdf.WPREST2RDF.main(WPREST2RDF.java:149)
    Caused by: java.lang.NullPointerException
      ... 7 more

I'm trying to figure out: 1. which files has the problematic GPML (I think it may be WP3322), 2. determine where it should be fixed (seems in GPML reader)...

@mkutmon, do you think this might be a good moment to migrate the GPML2RDF code to use the new library? Or should this be fixed in the old code?

**Comment by mkutmon** [comment]
I think this error comes from one of the new Reactome pathways. I don't think the library is ready yet. So either we need to fix the pathway or you need to have a look in the code where the error occurs (not sure if it isn't the pathway that's the problem - although this error message obviously doesn't help a lot).

**Comment by mkutmon** [comment]
problem was related to invalid GPML
