### ISSUE TITLE
ClassCastException with the CompexViz plugin

### ISSUE THREAD

**Issue by egonw** [PathVisio/pathvisio#70]
```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: org.pathvisio.core.model.Pathway cannot be cast to org.pathvisio.core.view.VPathway
        at org.pathvisio.complexviz.ComplexVizPlugin.applicationEvent(Unknown Source)
        at org.pathvisio.core.Engine.fireApplicationEvent(Engine.java:455)
        at org.pathvisio.core.Engine.newPathway(Engine.java:315)
        at org.pathvisio.gui.SwingEngine.newPathway(SwingEngine.java:260)
        at org.pathvisio.desktop.StandaloneActions$NewAction.actionPerformed(StandaloneActions.java:229)
```

**Comment by DeniseSl22** [comment]
What is this plugin needed for? @egonw

**Comment by egonw** [comment]
Not sure... IIRC, it's one of Anwesha's plugins? Or was this the one for Reactome pathways?

**Comment by DeniseSl22** [comment]
I think it does do something related to Reactome PWs; to connect the name of the complex in the PW to the groups below it.... but I'm not sure; not a major bug right>
