### ISSUE TITLE
pathvisio convert: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by ariutta** [PathVisio/pathvisio#99]
When I give call PathVisio convert like this on several different pathways:

```
java -Xmx512M -ea -classpath $CLASSPATH org.pathvisio.core.util.Converter input.gpml size100.png
java -Xmx512M -ea -classpath $CLASSPATH org.pathvisio.core.util.Converter input.gpml size200.png 200
```

I get this error:

> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
	at org.pathvisio.core.model.RasterImageExporter.exportAsImage(RasterImageExporter.java:136)
	at org.pathvisio.core.model.RasterImageExporter.doExport(RasterImageExporter.java:91)
	at org.pathvisio.core.Engine.exportPathway(Engine.java:140)
	at org.pathvisio.core.util.Converter.main(Converter.java:155)

**Comment by egonw** [comment]
Why not increase the heap size then? See https://stackoverflow.com/questions/1565388/increase-heap-size-in-java

```shell
java -Xmx1g -ea -classpath $CLASSPATH org.pathvisio.core.util.Converter input.gpml size200.png 200
```

Can you please try that? Or make it even 2GB? I have to do this for creating RDF too...

**Comment by ariutta** [comment]
@egonw, do you think it's actually putting 1GB of non-redundant, useful data into memory? Or could there be some kind of memory leak?

@AlexanderPico, does our wikipathways.org VM have enough memory to bump this up to 1GB? If I'm reading the following correctly, doing so might make the system start swapping, because we only have 210MB free:

```
ariutta@wikipathways-ws:~$ free -m
             total       used       free     shared    buffers     cached
Mem:          3953       3742        210         40        561       2491
-/+ buffers/cache:        689       3264
Swap:         4091         57       4034
```

Right now, the production site is set to 512MB. [LocalSettings.php](https://github.com/wikipathways/wikipathways.org/blob/f6e9c337c0a9029f0f329dc1ab156858b1433406/LocalSettings.php#L27) sets `$wgMaxShellMemory`:

```php
$wgMaxShellMemory = 512 * 1024;
```

and pathvisio is called like this in [Pathway.php](https://github.com/wikipathways/wikipathways.org/blob/f6e9c337c0a9029f0f329dc1ab156858b1433406/wpi/extensions/Pathways/Pathway.php#L1243):

```php
$maxMemoryM = intval($wgMaxShellMemory / 1024); //Max script memory on java program in megabytes
java -Xmx{$maxMemoryM}M -jar $basePath/bin/pathvisio_core.jar \"$gpmlFile\" \"$outFile\" 2>&1"
```

**Comment by egonw** [comment]
Ok, then increasingly the memory does not seem an option... About that memory leak... I cannot rule that out...
